version: '3'
services:
  mysql:
    container_name: db_mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - local


  app:
    container_name: app_server
    restart: always
    build: .
    ports:
      - '4000:4000'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
    networks:
      - local

networks:
  local:
    external: true
